name: 汉化发行

on:
  workflow_dispatch:
    inputs:
      release:
        description: "是否发行"
        type: boolean
      branch:
        type: string
        default: main
        description: "分支名"
    
  schedule:
    - cron: '0 15 * * *' # 每天北京时间23点（UTC+8, 等于UTC 15点）

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        backend: [vulkan]
        include:
          - backend: vulkan
            artifact_name: zed-release
            rustflags: ""

    steps:
      - name: Enable long paths in Git
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - uses: actions/checkout@v4

      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: ${{ inputs.branch || 'main' }}
          path: zed

      - name: 替换
        run: python3 step4-replace.py

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasip1

      - name: Rust 缓存
        uses: Swatinem/rust-cache@v2.7.3
        with:
          key: ${{ matrix.backend }}
          workspaces: "zed -> target"

      - name: Install PSToml module
        shell: pwsh
        run: Install-Module -Name PSToml -Scope CurrentUser -Force

      - name: Setup rustflags
        shell: pwsh
        run: ./Parse-Rustflags.ps1 ${{ matrix.rustflags }}

      - name: 编译发行版
        working-directory: zed
        run: cargo build --release --jobs 4

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: zed/target/release/zed.exe

  build-dpkg-x86:
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
      CC: clang-18
      CXX: clang++-18
    steps:
      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: ${{ inputs.branch || 'main' }}
          path: zed
      - name: 替换
        run: python3 step4-replace.py

      - name: 将 Rust 添加到 PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Setup Sentry CLI
        uses: matbour/setup-sentry-cli@3e938c54b3018bdd019973689ef984e033b0454b

      - name: 设置
        run: ./zed/script/linux
      - name: 下载 wasi sdk
        run: ./zed/script/download-wasi-sdk

      - name: 安装 clang-18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: 编译
        run: |
         cd zed
          ./script/bundle-linux

      - name: 移动文件
        run: mv zed/target/release/zed*.tar.gz zed-linux-x86_64.tar.gz

      - name: 解压文件
        run: tar -xvf zed-linux-x86_64.tar.gz

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux-x86_64
          path: zed-linux-x86_64.tar.gz

      - name: 移动
        run: mv zed-dev.app deb/usr

      - name: 权限修复
        run: chmod 775 deb -R

      - name: 编译
        run: dpkg-deb --build deb

      - name: 改名
        run: mv deb.deb zed-linux-x86_64.deb

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux-x86_64.deb
          path: zed-linux-x86_64.deb

      - name: 上传 zed-remote-server-linux-x86_64.gz
        uses: actions/upload-artifact@v4
        with:
          name: zed-remote-server-linux-x86_64.gz
          path: zed/target/zed-remote-server-linux-x86_64.gz

  build-dpkg-arm:
    runs-on: ubuntu-22.04-arm
    env:
      CARGO_TERM_COLOR: always
      CC: clang-18
      CXX: clang++-18

    steps:
      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: ${{ inputs.branch || 'main' }}
          path: zed
      - name: 替换
        run: python3 step4-replace.py

      - name: 设置
        run: ./zed/script/linux

      - name: 安装 clang-18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          
      - name: 下载 wasi sdk
        run: ./zed/script/download-wasi-sdk
      - name: 编译
        run: |
          cd zed
          ./script/bundle-linux

      - name: 移动
        run: mv zed/target/release/zed*.tar.gz zed-linux-arm64.tar.gz

      - name: 解压文件
        run: tar -xvf zed-linux-arm64.tar.gz

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux-arm64
          path: zed-linux-arm64.tar.gz

      - name: 移动
        run: mv zed-dev.app deb-arm/usr

      - name: 权限修复
        run: chmod 775 deb-arm -R

      - name: 编译
        run: dpkg-deb --build deb-arm

      - name: 改名
        run: mv deb-arm.deb zed-linux-arm64.deb

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux-arm64.deb
          path: zed-linux-arm64.deb

      - name: 上传 zed-remote-server-linux-aarch64.gz
        uses: actions/upload-artifact@v4
        with:
          name: zed-remote-server-linux-aarch64.gz
          path: zed/target/zed-remote-server-linux-aarch64.gz

  build-mac:
    name: 编译 (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MacOS arm64
            os: macos-latest
            target: aarch64-apple-darwin
            dmg: Zed-aarch64.dmg
          - name: MacOS x86_64
            os: macos-15-intel
            target: x86_64-apple-darwin
            dmg: Zed-x86_64.dmg

    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1

    steps:
      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"

      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Checkout 当前仓库
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: 手动同步 zed 源代码
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: zed-industries/zed
          ref: ${{ inputs.branch }}
          path: zed

      - name: 替换
        run: python3 step4-replace.py

      - name: Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Cmake
        run: brew install cmake

      - name: 安装 Rust target
        run: |
          rustup target add ${{ matrix.target }}

      - name: steps::clear_target_dir_if_large
        run: ./zed/script/clear-target-dir-if-larger-than 300

      - name: run_bundling::bundle_mac::bundle_mac
        run: |
          cd zed
          ./script/bundle-mac ${{ matrix.target }}

      - name: 上传（按架构）
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            zed/target/${{ matrix.target }}/release/Zed-*.dmg
            zed/target/zed-remote-server-*.gz

  release:
    if: (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && inputs.release)
    needs: [build-windows, build-dpkg-x86, build-mac]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get the current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create release directories and zip
        run: |
          mkdir -p zed-release
          mv artifacts/zed-release/zed.exe zed-release/
          zip -r zed-windows.zip zed-release/*

      - name: linux
        run: |
          mv artifacts/zed-linux-x86_64.deb/zed-linux-x86_64.deb zed-linux-x86_64.deb
          # mv artifacts/zed-linux-arm64.deb/zed-linux-arm64.deb zed-linux-arm64.deb
          mv artifacts/zed-linux-x86_64/zed-linux-x86_64.tar.gz zed-linux-x86_64.tar.gz
          # mv artifacts/zed-linux-arm64/zed-linux-arm64.tar.gz zed-linux-arm64.tar.gz
          mv artifacts/zed-remote-server-linux-x86_64.gz/zed-remote-server-linux-x86_64.gz zed-remote-server-linux-x86_64.gz
          # mv artifacts/zed-remote-server-linux-aarch64.gz/zed-remote-server-linux-aarch64.gz zed-remote-server-linux-aarch64.gz


      - name: macos
        run: |
          mv artifacts/aarch64-apple-darwin/aarch64-apple-darwin/release/Zed-*.dmg zed-macos-aarch64.dmg
          mv artifacts/aarch64-apple-darwin/zed-remote-server-*.gz zed-remote-server-macos-aarch64.gz
          mv artifacts/x86_64-apple-darwin/x86_64-apple-darwin/release/Zed-*.dmg zed-macos-x86_64.dmg
          mv artifacts/x86_64-apple-darwin/zed-remote-server-*.gz zed-remote-server-macos-x86_64.gz

      - name: build sha256
        run: |
          # sha256sum zed-windows.zip zed-linux-x86_64.deb zed-linux-arm64.deb zed-linux-x86_64.tar.gz zed-linux-arm64.tar.gz > sha256sums.txt
          sha256sum zed-windows.zip zed-linux-x86_64.deb zed-linux-x86_64.tar.gz zed-macos-aarch64.dmg zed-macos-x86_64.dmg zed-remote-server-linux-x86_64.gz zed-remote-server-macos-aarch64.gz zed-remote-server-macos-x86_64.gz > sha256sums.txt

      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: |
            zed-windows.zip
            zed-linux-x86_64.deb
            zed-linux-arm64.deb
            zed-linux-x86_64.tar.gz
            zed-linux-arm64.tar.gz
            zed-macos-aarch64.dmg
            zed-macos-x86_64.dmg
            zed-remote-server-linux-x86_64.gz
            zed-remote-server-linux-aarch64.gz
            zed-remote-server-macos-aarch64.gz
            zed-remote-server-macos-x86_64.gz
            sha256sums.txt
