name: 词条提取
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        description: "分支名"
permissions:
  contents: read

jobs:
  extract:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: 安装依赖
        run: pip install pyyaml
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: ${{ inputs.branch }}
          path: zed
      - name: 提取
        run: python3 step1-extract.py
      - name: 删除多余词条
        run: python3 step2-delete.py
      - name: 上传词条文件
        uses: actions/upload-artifact@v4
        with:
          name: string
          path: string.json
